In [18]:
pip install --grade pillow

Note: you may need to restart the kernel to use updated packages.



Usage:   
  C:\Users\Darya\anaconda3\python.exe -m pip install [options] <requirement specifier> [package-index-options] ...
  C:\Users\Darya\anaconda3\python.exe -m pip install [options] -r <requirements file> [package-index-options] ...
  C:\Users\Darya\anaconda3\python.exe -m pip install [options] [-e] <vcs project url> ...
  C:\Users\Darya\anaconda3\python.exe -m pip install [options] [-e] <local project path> ...
  C:\Users\Darya\anaconda3\python.exe -m pip install [options] <archive url/path> ...

no such option: --grade


task1

In [28]:
import numpy as np
a = np.array ([[1,6],
             [2,8],
             [3,11],
             [3,10],
             [1,7]])
mean_a = np.array([np.mean(a, axis=0)])
print (mean_a)

[[2.  8.4]]


In [25]:
print (a)

[[ 1  6]
 [ 2  8]
 [ 3 11]
 [ 3 10]
 [ 1  7]]


task2

In [31]:
a_centered = a + mean_a
print (a_centered)

[[ 3.  14.4]
 [ 4.  16.4]
 [ 5.  19.4]
 [ 5.  18.4]
 [ 3.  15.4]]


task3

In [38]:
a_centered_sp = a_centered[:,0].dot(a_centered[:,1])
print (a_centered_sp)
ratio = a_centered_sp / (a_centered[:,0].size - 1)
print (ratio)

344.0
86.0


task4

In [39]:
m = a.T
print (m)
np.cov

[[ 1  2  3  3  1]
 [ 6  8 11 10  7]]


<function numpy.cov(m, y=None, rowvar=True, bias=False, ddof=None, fweights=None, aweights=None, *, dtype=None)>

# PANDAS

task1

In [52]:
import pandas as pd
authors = pd.DataFrame({'author_id':[1,2,3],
                       'author_name': ['Тургенев', 'Чехов', 'Достоевский']},
                      columns = ['author_id', 'author_name'])
print (authors)

   author_id  author_name
0          1     Тургенев
1          2        Чехов
2          3  Достоевский


In [58]:
books = pd.DataFrame({'author_id':[1,1,1,2,2,3,3],
                      'book_title':['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 
                      'Дама с собачкой','Гроза', 'Таланты и поклонники'], 
                      'price':[500, 800, 200, 100, 400, 400, 500]},
                      columns = ['author_id', 'book_title', 'price'])
print (books)

   author_id            book_title  price
0          1           Отцы и дети    500
1          1                 Рудин    800
2          1     Дворянское гнездо    200
3          2      Толстый и тонкий    100
4          2       Дама с собачкой    400
5          3                 Гроза    400
6          3  Таланты и поклонники    500


task2

In [96]:
authors_price = pd.merge(authors, books, on='author_id', how='inner')
print(authors_price)

   author_id  author_name            book_title  price
0          1     Тургенев           Отцы и дети    500
1          1     Тургенев                 Рудин    800
2          1     Тургенев     Дворянское гнездо    200
3          2        Чехов      Толстый и тонкий    100
4          2        Чехов       Дама с собачкой    400
5          3  Достоевский                 Гроза    400
6          3  Достоевский  Таланты и поклонники    500


task3

In [148]:
top5 = authors_price.nlargest(5,'price')
print(top5)

   author_id  author_name            book_title  price
1          1     Тургенев                 Рудин    800
0          1     Тургенев           Отцы и дети    500
6          3  Достоевский  Таланты и поклонники    500
4          2        Чехов       Дама с собачкой    400
5          3  Достоевский                 Гроза    400


task4

In [152]:
authors_unique = authors_price.drop_duplicates('author_name')
print(authors_unique)
authors_stat = authors_unique.drop(['book_title', 'price'], axis=1)
print(authors_stat)
Tur = authors_price[authors_price['author_id']==1]
Che = authors_price[authors_price['author_id']==2]
Dos = authors_price[authors_price['author_id']==3]
price_data = pd.DataFrame({'author_id': [1,2,3],
                            'price_min': [Tur['price'].min(), Che['price'].min(), Dos['price'].min()],
                            'price_max': [Tur['price'].max(), Che['price'].max(), Dos['price'].max()],
                            'price_mean': [Tur['price'].mean(), Che['price'].mean(), Dos['price'].mean()]},
                            columns = ['author_id','price_min', 'price_max', 'price_mean'])
print(price_data)
authors_stat = pd.merge(authors_stat, price_data, on='author_id', how='inner')
print(authors_stat)


   author_id  author_name        book_title  price
0          1     Тургенев       Отцы и дети    500
3          2        Чехов  Толстый и тонкий    100
5          3  Достоевский             Гроза    400
   author_id  author_name
0          1     Тургенев
3          2        Чехов
5          3  Достоевский
   author_id  price_min  price_max  price_mean
0          1        200        800       500.0
1          2        100        400       250.0
2          3        400        500       450.0
   author_id  author_name  price_min  price_max  price_mean
0          1     Тургенев        200        800       500.0
1          2        Чехов        100        400       250.0
2          3  Достоевский        400        500       450.0


Task5

In [176]:
cover = ['т', 'м', 'м', 'т', 'т', 'м', 'м']
authors_price['cover']=cover
print(authors_price)
authors_price1 = pd.pivot_table(authors_price, index = ['author_name', 'cover'], values=['price'], aggfunc=np.sum).T
print(authors_price1)




   author_id  author_name            book_title  price cover
0          1     Тургенев           Отцы и дети    500     т
1          1     Тургенев                 Рудин    800     м
2          1     Тургенев     Дворянское гнездо    200     м
3          2        Чехов      Толстый и тонкий    100     т
4          2        Чехов       Дама с собачкой    400     т
5          3  Достоевский                 Гроза    400     м
6          3  Достоевский  Таланты и поклонники    500     м
author_name Достоевский Тургенев      Чехов
cover                 м        м    т     т
price               900     1000  500   500


In [178]:
authors_price1.to_pickle('book_info.pkl')

In [179]:
book=pd.read_pickle('book_info.pkl')

In [180]:
print(book)

author_name Достоевский Тургенев      Чехов
cover                 м        м    т     т
price               900     1000  500   500
